MealPlanner/ViewModels/MealPlanViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using MealPlanner.Models;

namespace MealPlanner.ViewModels
{
    public class MealPlanViewModel
    {
        public MealPlan MealPlan { get; set; }
        public List<decimal> TotalCalories { get; set; }
        public int TDEE { get; set; }
        public int DailyCalorieAmount { get; set; }
        public int CarbsAmount { get; set; }
        public int CarbsPercent { get; set; }
        public int FatAmount { get; set; }
        public int FatPercent { get; set; }
        public int ProteinAmount { get; set; }
        public int ProteinPercent { get; set; }
    }
}

MealPlanner/Controllers/MealController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MealPlanner.Models;
using MealPlanner.ViewModels;
using MealPlanner.Models.Repositories;

namespace MealPlanner.Controllers
{
    public class MealController : Controller
    {
        private readonly ILogger<MealController> _logger;
        private readonly IMealRepository mealRepository;
        private readonly ICategoryRepository categoryRepository;

        public MealController(ILogger<MealController> logger, IMealRepository mealRepository, ICategoryRepository categoryRepository)
        {
            _logger = logger;
            this.mealRepository = mealRepository;
            this.categoryRepository = categoryRepository;
        }

        public ViewResult List(string category)
        {
            IEnumerable<Meal> meals;
            string currentCategory;
            if (string.IsNullOrEmpty(category))
            {
                meals = mealRepository.AllMeals.OrderBy(p => p.MealId);
                currentCategory = "All meals";
            }
            else
            {
                meals = mealRepository.AllMeals.Where(p => p.Category.CategoryName == category)
                    .OrderBy(p => p.MealId);
                currentCategory = categoryRepository.AllCategories.FirstOrDefault(c => c.CategoryName == category)?.CategoryName;
            }
            return View(new MealsListViewModel { 
                Meals = meals,
                CurrentCategory = currentCategory
            });
        }

        public IActionResult Details(int id)
        {
            var meal = mealRepository.GetMealById(id);
            if (meal == null) return NotFound();
            return View(meal);
        }
    }
}

MealPlanner/Controllers/MealPlanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using MealPlanner.Models;
using MealPlanner.Models.Repositories;
using MealPlanner.Modles.Repositories;
using MealPlanner.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace MealPlanner.Controllers
{
    [Authorize]
    public class MealPlanController:Controller
    {
        private readonly IMealRepository mealRepository;
        private readonly MealPlan mealPlan;
        private readonly IPersonRepository personRepository;
        private readonly UserManager<User> userManager;
        private bool personalised;


        public MealPlanController(IMealRepository mealRepository, MealPlan mealPlan, IPersonRepository personRepository, UserManager<User> userManager)
        {
            this.mealRepository = mealRepository;
            this.mealPlan = mealPlan;
            this.personRepository = personRepository;
            this.userManager = userManager;
        }
        public ViewResult Index()
        {
            var id = userManager.GetUserId(User); // Get user id:
            var user = personRepository.getUser(id);
            var totalCalories = personRepository.getUserDailyCalories(id);
            if (!personalised)
            {
                mealRepository.AddPersonalMeals(mealPlan,  totalCalories);
                personalised = true;
            }

            var items = mealPlan.GetMealPlanItems();

            

            mealPlan.MealPlanItems = items;
            ClaimsPrincipal currentUser = this.User;

            var TDEE = personRepository.calculateUserTDEE(id);
            List<int> macros = personRepository.calculateMacros(id);
            int proteinPercent = (int)Math.Round((double)macros.ElementAt(0) * 4 / totalCalories * 100);
            int fatPercent = (int)Math.Round((double)macros.ElementAt(1) * 9 / totalCalories * 100);
            int carbsPercent = (int)Math.Round((double)macros.ElementAt(2) * 4 / totalCalories * 100);


            var mealPlanViewModel = new MealPlanViewModel()
            {
                MealPlan = mealPlan,
                TDEE = personRepository.calculateUserTDEE(id),
                TotalCalories = mealPlan.GetMealPlanTotalCalories(),
                DailyCalorieAmount = totalCalories,
                ProteinAmount = macros.ElementAt(0),
                FatAmount = macros.ElementAt(1),
                CarbsAmount = macros.ElementAt(2),
                ProteinPercent = proteinPercent,
                CarbsPercent = carbsPercent,
                FatPercent = fatPercent
            };
            mealPlanViewModel.MealPlan.MealPlanItems.OrderBy(x => x.DayOfWeek);
            return View(mealPlanViewModel);
        }

        public RedirectToActionResult AddToMealPlan(int day, int mealId)
        {
            Meal selectedMeal = mealRepository.AllMeals.FirstOrDefault(p => p.MealId == mealId);

            if (selectedMeal != null)
            {
                mealPlan.AddToPlan(selectedMeal,day , 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromMealPlan(int mealId, DayOfWeek dayOfWeek)
        {
            var selectedPie = mealRepository.AllMeals.FirstOrDefault(p => p.MealId == mealId);

            if (selectedPie != null)
            {
                mealPlan.RemoveFromPlan(selectedPie, (int)dayOfWeek);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult ClearMealPlan()
        {

            mealPlan.ClearMealPlan();
            return RedirectToAction("Index");
        }


    }
}

MealPlanner/Views/MealPlan/Index.cshtml
@model MealPlanViewModel

<h2>Your mealPlan</h2>


<div>
    <table class="table">
        <tbody>
            <tr>
                <td>Metabolic Data</td>
                <td colspan="2">TDEE: @Model.TDEE kcal </td>
            </tr>
            <tr>
                <td>Daily calorie goal:</td>
                <td colspan="2">@Model.DailyCalorieAmount kcal</td>
            </tr>
            <tr>
                <td>Your Ideal Macros:</td>
                <td colspan="2">Pro:@Model.ProteinAmount g&nbsp;&nbsp;Carb::@Model.CarbsAmount g&nbsp;&nbsp;Fat: @Model.FatAmount g</td>

            </tr>
            <tr>
                <td></td>
                <td colspan="2">Pro:@Model.ProteinPercent %&nbsp;&nbsp;Carb: @Model.CarbsPercent %&nbsp;&nbsp;Fat: @Model.FatPercent %</td>

            </tr>
        </tbody>
    </table>
</div>

@for (int i = 0; i < 7; i++)
{
    <h3 colspan="3" class="text-center">@((DayOfWeek)i)</h3>

    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Selected amount</th>
                <th>Meal</th>
                <th>Protein</th>
                <th>Fat</th>
                <th>Carbs</th>
                <th class="text-right">Subtotal</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.MealPlan.MealPlanItems.Where(x => x.DayOfWeek == (DayOfWeek)i))
            {

            <tr>
                <td class="text-center">@line.Amount</td>
                <td class="text-left"> <a asp-controller="Meal" asp-action="Details" asp-route-id="@line.Meal.MealId">@line.Meal.Name</a></td>
                <td>@line.Meal.ProteinContent</td>
                <td>@line.Meal.FatContent g</td>
                <td>@line.Meal.CarbohidrateContent g</td>

                <td class="text-right">
                    @((line.Amount * line.Meal.Calories)) kcal
                </td>
                <td>
                    <div class="addToPlan">
                        <p class="button">
                            <a class="btn btn-primary"
                               asp-controller="MealPlan"
                               asp-action="RemoveFromMealPlan"
                               asp-route-dayOfWeek="@line.DayOfWeek"
                               asp-route-mealId="@line.Meal.MealId">Remove from plan</a>
                        </p>
                    </div>
                </td>
            </tr>


            }

        </tbody>
        <tfoot>
            <tr>
                <td>Used calories:</td>
                <td colspan="3">
                    <div id="myProgress">
                        <div style="width:@Math.Round((Model.TotalCalories.ElementAt(i)/(decimal)Model.DailyCalorieAmount * 100))%;" id="myBar"></div>
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="2" class="text-right">Total calories:</td>
                <td class="text-right">
                    @Model.TotalCalories.ElementAt(i).ToString()
                </td>
            </tr>

        </tfoot>
    </table>


}